/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_DEV_RPC_ADMINVAPFACE_H_
#define JSONRPC_CPP_STUB_DEV_RPC_ADMINVAPFACE_H_

#include "ModularServer.h"

namespace dev {
    namespace rpc {
        class AdminVapFace : public ServerInterface<AdminVapFace>
        {
            public:
                AdminVapFace()
                {
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_blockQueueStatus", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_blockQueueStatusI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_setAskPrice", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_setAskPriceI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_setBidPrice", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_setBidPriceI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_setMining", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_BOOLEAN,"param2",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_setMiningI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_findBlock", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_findBlockI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_blockQueueFirstUnknown", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, "param1",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_blockQueueFirstUnknownI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_blockQueueRetryUnknown", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_blockQueueRetryUnknownI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_allAccounts", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_ARRAY, "param1",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_allAccountsI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_newAccount", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_OBJECT,"param2",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_newAccountI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_setMiningBenefactor", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_setMiningBenefactorI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_inspect", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_inspectI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_reprocess", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_reprocessI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_vmTrace", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_INTEGER,"param3",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_vmTraceI);
                    this->bindAndAddMethod(jsonrpc::Procedure("admin_vap_getReceiptByHashAndIndex", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_INTEGER,"param3",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::admin_vap_getReceiptByHashAndIndexI);
                    this->bindAndAddMethod(jsonrpc::Procedure("miner_start", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_INTEGER, NULL), &dev::rpc::AdminVapFace::miner_startI);
                    this->bindAndAddMethod(jsonrpc::Procedure("miner_stop", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN,  NULL), &dev::rpc::AdminVapFace::miner_stopI);
                    this->bindAndAddMethod(jsonrpc::Procedure("miner_setVaporbase", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::miner_setVaporbaseI);
                    this->bindAndAddMethod(jsonrpc::Procedure("miner_setExtra", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::miner_setExtraI);
                    this->bindAndAddMethod(jsonrpc::Procedure("miner_setGasPrice", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING, NULL), &dev::rpc::AdminVapFace::miner_setGasPriceI);
                    this->bindAndAddMethod(jsonrpc::Procedure("miner_hashrate", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING,  NULL), &dev::rpc::AdminVapFace::miner_hashrateI);
                }

                inline virtual void admin_vap_blockQueueStatusI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_blockQueueStatus(request[0u].asString());
                }
                inline virtual void admin_vap_setAskPriceI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_setAskPrice(request[0u].asString(), request[1u].asString());
                }
                inline virtual void admin_vap_setBidPriceI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_setBidPrice(request[0u].asString(), request[1u].asString());
                }
                inline virtual void admin_vap_setMiningI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_setMining(request[0u].asBool(), request[1u].asString());
                }
                inline virtual void admin_vap_findBlockI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_findBlock(request[0u].asString(), request[1u].asString());
                }
                inline virtual void admin_vap_blockQueueFirstUnknownI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_blockQueueFirstUnknown(request[0u].asString());
                }
                inline virtual void admin_vap_blockQueueRetryUnknownI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_blockQueueRetryUnknown(request[0u].asString());
                }
                inline virtual void admin_vap_allAccountsI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_allAccounts(request[0u].asString());
                }
                inline virtual void admin_vap_newAccountI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_newAccount(request[0u], request[1u].asString());
                }
                inline virtual void admin_vap_setMiningBenefactorI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_setMiningBenefactor(request[0u].asString(), request[1u].asString());
                }
                inline virtual void admin_vap_inspectI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_inspect(request[0u].asString(), request[1u].asString());
                }
                inline virtual void admin_vap_reprocessI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_reprocess(request[0u].asString(), request[1u].asString());
                }
                inline virtual void admin_vap_vmTraceI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_vmTrace(request[0u].asString(), request[1u].asInt(), request[2u].asString());
                }
                inline virtual void admin_vap_getReceiptByHashAndIndexI(const Json::Value &request, Json::Value &response)
                {
                    response = this->admin_vap_getReceiptByHashAndIndex(request[0u].asString(), request[1u].asInt(), request[2u].asString());
                }
                inline virtual void miner_startI(const Json::Value &request, Json::Value &response)
                {
                    response = this->miner_start(request[0u].asInt());
                }
                inline virtual void miner_stopI(const Json::Value &request, Json::Value &response)
                {
                    (void)request;
                    response = this->miner_stop();
                }
                inline virtual void miner_setVaporbaseI(const Json::Value &request, Json::Value &response)
                {
                    response = this->miner_setVaporbase(request[0u].asString());
                }
                inline virtual void miner_setExtraI(const Json::Value &request, Json::Value &response)
                {
                    response = this->miner_setExtra(request[0u].asString());
                }
                inline virtual void miner_setGasPriceI(const Json::Value &request, Json::Value &response)
                {
                    response = this->miner_setGasPrice(request[0u].asString());
                }
                inline virtual void miner_hashrateI(const Json::Value &request, Json::Value &response)
                {
                    (void)request;
                    response = this->miner_hashrate();
                }
                virtual Json::Value admin_vap_blockQueueStatus(const std::string& param1) = 0;
                virtual bool admin_vap_setAskPrice(const std::string& param1, const std::string& param2) = 0;
                virtual bool admin_vap_setBidPrice(const std::string& param1, const std::string& param2) = 0;
                virtual bool admin_vap_setMining(bool param1, const std::string& param2) = 0;
                virtual Json::Value admin_vap_findBlock(const std::string& param1, const std::string& param2) = 0;
                virtual std::string admin_vap_blockQueueFirstUnknown(const std::string& param1) = 0;
                virtual bool admin_vap_blockQueueRetryUnknown(const std::string& param1) = 0;
                virtual Json::Value admin_vap_allAccounts(const std::string& param1) = 0;
                virtual Json::Value admin_vap_newAccount(const Json::Value& param1, const std::string& param2) = 0;
                virtual bool admin_vap_setMiningBenefactor(const std::string& param1, const std::string& param2) = 0;
                virtual Json::Value admin_vap_inspect(const std::string& param1, const std::string& param2) = 0;
                virtual Json::Value admin_vap_reprocess(const std::string& param1, const std::string& param2) = 0;
                virtual Json::Value admin_vap_vmTrace(const std::string& param1, int param2, const std::string& param3) = 0;
                virtual Json::Value admin_vap_getReceiptByHashAndIndex(const std::string& param1, int param2, const std::string& param3) = 0;
                virtual bool miner_start(int param1) = 0;
                virtual bool miner_stop() = 0;
                virtual bool miner_setVaporbase(const std::string& param1) = 0;
                virtual bool miner_setExtra(const std::string& param1) = 0;
                virtual bool miner_setGasPrice(const std::string& param1) = 0;
                virtual std::string miner_hashrate() = 0;
        };

    }
}
#endif //JSONRPC_CPP_STUB_DEV_RPC_ADMINVAPFACE_H_
