#------------------------------------------------------------------------------
# Appveyor configuration file for cpp-vapory.
#
# The documentation for cpp-vapory is hosted at http://cpp-vapory.co
#
# ------------------------------------------------------------------------------
# This file is part of cpp-vapory.
#
# cpp-vapory is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cpp-vapory is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cpp-vapory.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

branches:
  only:
    - master
    - develop
    - appveyor
    - hunter
os: Visual Studio 2015
configuration:
  - RelWithDebInfo
environment:
  TESTS: On
  GITHUB_USER_PASSWORD:
    secure: 7TuNppxpvI3M/IF1PfvzZ8LluCeCQAsdFoJY+KhNv/pe/rAw5HEsTjqdbyM1mEtd
cache:
  - build/deps -> cmake/ProjectLibFF.cmake
install:
  - git submodule update --init --recursive
  - scripts/install_deps.bat
  - set VAPORY_DEPS_PATH=%APPVEYOR_BUILD_FOLDER%\deps
before_build: |
  if not exist build mkdir build
  cd build
  cmake -G "Visual Studio 14 2015 Win64" .. -DTESTS=%TESTS% -DVVMJIT=OFF
build_script:
    - msbuild cpp-vapory.sln /p:Configuration=%CONFIGURATION% /m:%NUMBER_OF_PROCESSORS% /v:minimal
    - cd %APPVEYOR_BUILD_FOLDER%
    - scripts\release.bat %CONFIGURATION% %VAPORY_DEPS_PATH% %TESTS%
after_build:
  ps: |
    if (-not $env:appveyor_pull_request_number) {
      pip install --user requests
      cmake --build build --target hunter_upload_cache
    }
test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - scripts\tests.bat %TESTS% %CONFIGURATION% %APPVEYOR_BUILD_FOLDER% %VAPORY_DEPS_PATH%
artifacts:
    - path: cpp-vapory-windows.zip
      name: cpp-vapory-windows-zip

# This is the deploy target for Windows which generates ZIPs per commit.
# We are in agreement that generating ZIPs per commit for the develop
# branch is probably just noise, so we only run this deployment target
# on 'release'.
#
# See https://www.appveyor.com/docs/deployment/github for information
# on GitHub Releases in Appveyor.
#
# You need to generate a GitHub personal access token for Appveyor
# See https://github.com/settings/tokens for more information on that.
# The token you generate there (in an encrypted form) is what is
# passed to this deployment target in the 'auth_token' parameter
# below.
deploy:
    prerelease: true
    provider: GitHub
    auth_token:
        secure: yukM9mHUbzuZSS5WSBLKSW0yGJerJEqAXkFhDhSHBBcKJE7GAryjQsdO9Kxh3yRv
    artifact: cpp-vapory-windows-zip
    on:
        branch: release

# Disable slightly annoying AppVeyorBot.  The comments it adds onto Github issues are
# redundant with the "Checks Passed/Failure" detail which is already on the issues.
notifications:
    - provider: GitHubPullRequest
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: false
