default-steps: &default-steps
  - checkout

  - run:
      name: "Init submodules"
      command: git submodule update --init

  - run:
      name: "Configure"
      command: |
        mkdir -p build && cd build
        cmake .. -G "${GENERATOR}" -DCOVERAGE=ON
        echo $CXX > compiler

  - cache-restore:
      name: "Restore dependencies cache"
      key: &deps-cache-key deps-0-{{ checksum "build/compiler" }}-{{ checksum "cmake/ProjectJsonRpcCpp.cmake" }}

  - run:
      name: "Upload Hunter cache"
      command: |
        if [ ! "$CIRCLE_PR_NUMBER" ]; then  # Skip forked PRs.
          cmake --build build --target hunter_upload_cache
        fi

  - run:
      name: "Build"
      command: cmake --build build -- -j $BUILD_PARALLEL_JOBS

  - cache-save:
      name: "Save dependencies cache"
      key: *deps-cache-key
      paths:
        - ~/cpp-vapory/build/deps

  - store_artifacts:
      path: build/vap/vap
      destination: vap

  - cache-restore:
      name: "Restore Vapash DAG file"
      key: vapash-dag0

  - run:
      name: "Test"
      pwd: ~/cpp-vapory/build
      command: |
        export VAPORY_TEST_PATH=~/cpp-vapory/test/jsontests
        export TMPDIR=/dev/shm
        CTEST_OUTPUT_ON_FAILURE=1 ctest -j8

  - cache-save:
      name: "Save Vapash DAG file"
      key: vapash-dag0
      paths:
        - ~/.vapash/full-R23-0000000000000000

  - run:
      name: "Code coverage"
      pwd: ~/cpp-vapory/build
      command: |
        bash <(curl -s https://codecov.io/bash) -X fix

version: 2
jobs:

  default-clang5-ninja:
    environment:
      - CXX: clang++-5.0
      - CC:  clang-5.0
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 8
    docker:
      - image: vapory/cpp-build-env
    working_directory: ~/cpp-vapory
    steps: *default-steps

  debug-gcc6-ninja:
    environment:
      - BUILD_TYPE: Debug
      - CXX: g++-6
      - CC:  gcc-6
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 4
    docker:
      - image: vapory/cpp-build-env
    working_directory: ~/cpp-vapory
    steps: *default-steps

workflows:
  version: 2
  cpp-vapory:
    jobs:
      - default-clang5-ninja
      - debug-gcc6-ninja