name: cpp-vapory
version: master
summary: blockchain app platform
description: Vapory C++ project

grade: devel
confinement: devmode

apps:
  vap:
    command: vap
  vapvm:
    command: vapvm

parts:
  cpp-vapory:
    source: .
    source-type: git
    plugin: cmake
    build-packages:
      - build-essential
      - libgmp-dev
      - libleveldb-dev
