name: cpp-vapory
version: master
summary: blockchain app platform
description: Vapory C++ project

grade: devel
confinement: devmode

apps:
  vap:
    command: vap
  vapkey:
    command: vapkey
  vapvm:
    command: vapvm
  rlp:
    command: rlp

parts:
  cpp-vapory:
    source: .
    plugin: cmake
    build-packages:
      - build-essential
      - libboost-all-dev
      - libgmp-dev
      - libleveldb-dev
      - libmicrohttpd-dev
      - libminiupnpc-dev
