#!/usr/bin/env sh
mkdir -p ~/.vapory ~/.web3

# check if sudo is necessary
if ! id -nG $(whoami)|grep -qw "docker"; then SUDO='sudo'; else SUDO=''; fi

$SUDO docker run --rm -it \
           -p 127.0.0.1:8545:8545 \
           -p 0.0.0.0:30303:30303 \
           -v ~/.vapory:/.vapory \
           -v ~/.web3:/.web3 \
           -e HOME=/ \
           --user $(id -u):$(id -g) \
           vapory/client-cpp $@

